FROM centos
RUN yum install -y java
VOLUME /tmp
ADD target/prueba-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./unrandom","-jar","/app.jar"]